[MeterOverloadBtnHi]
Meter=Image
Group=Modules | OverloadButtons
ImageName=#@#/shipui/overloadbtnhion.png
X=(170 + #OffsetX#)
Y=(55 + #OffsetY#)

[MeterOverloadBtnMd]
Meter=Image
Group=Modules | OverloadButtons
ImageName=#@#/shipui/overloadbtnmedon.png
X=(178 + #OffsetX#)
Y=(69 + #OffsetY#)

[MeterOverloadBtnLo]
Meter=Image
Group=Modules | OverloadButtons
ImageName=#@#/shipui/overloadbtnlooff.png
X=(170 + #OffsetX#)
Y=(83 + #OffsetY#)